baseURL = "/"
languageCode = "es-es"
title = "PowerTrader EnergyFlash"
theme = "PaperMod"

[params]
    env = "production"
    # Esto desactiva el código que está dando error de comas
    schema = false
