baseURL = "/"
languageCode = "es-es"
title = "Energy"
theme = "PaperMod"

[params]
    # Desactivamos absolutamente todo lo que pueda generar c√≥digo JSON
    disableShare = true
    disableHLJS = true
    editPost = false
    ShowReadingTime = false
    ShowCodeCopyButtons = false
