baseURL = "/"
languageCode = "es-es"
title = "PowerTrader EnergyFlash"
theme = "PaperMod"

[params]
    env = "production"
    description = "Inteligencia diaria de mercados"
    # AÃ±adimos esto para que el Schema no falle
    [params.schema]
        publisherType = "Organization"
        name = "PowerTrader"
