baseURL = "/"
languageCode = "es-es"
title = "PowerTrader EnergyFlash"
theme = "PaperMod"

[params]
    env = "production"
    title = "PowerTrader EnergyFlash"
    description = "Inteligencia diaria de mercados"
