# PEGA AQUÍ LA DIRECCIÓN QUE HAS COPIADO DE NETLIFY
baseURL = "https://energyflash.netlify.app/"
languageCode = "es-es"
title = "PowerTrader EnergyFlash"
theme = "PaperMod"

[params]
    env = "production"
    title = "PowerTrader EnergyFlash"
    description = "Inteligencia diaria de mercados"
    author = "PowerTrader"

    [params.assets]
        disableHLJS = true
