baseURL = "/"
languageCode = "es-es"
title = "PowerTrader EnergyFlash"
theme = "PaperMod"

[params]
    env = "production"
    title = "PowerTrader EnergyFlash"
    description = "Inteligencia diaria de mercados"
    
    # IMPORTANTE: No añadimos ni 'editPost' ni 'schema' aquí.
    # Al no ponerlos, el tema simplemente no carga esas funciones.
    # Así evitamos el error de tipos.

    [params.assets]
        disableHLJS = true
